# Generated by Django 3.2 on 2021-04-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='id_scan',
            new_name='scan',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='id_asset',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='id_asset',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='id_client',
            new_name='client',
        ),
    ]
