# Generated by Django 3.2 on 2021-04-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210421_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='data_output',
        ),
    ]
