# Generated by Django 3.2 on 2021-04-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_port_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
            preserve_default=False,
        ),
    ]
