# Generated by Django 3.2 on 2021-04-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_port_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='client',
        ),
        migrations.AddField(
            model_name='port',
            name='scan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.scan'),
            preserve_default=False,
        ),
    ]
