# Generated by Django 3.2 on 2021-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_temp_subdomains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_subdomains',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
