# Generated by Django 3.2 on 2021-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_temp_subdomains_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_type',
            field=models.CharField(choices=[('ip', 'publicIP'), ('subdom', 'subdomain')], max_length=6),
        ),
    ]
